# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-28 18:30
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(editable=False, max_length=250)),
                ('rating', models.IntegerField(choices=[(5, b'Excelent'), (4, b'Very Good'), (3, b'Good'), (2, b'Not Good'), (1, b'Bad')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('title', models.CharField(editable=False, max_length=250)),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(default=b'127.0.0.1')),
                ('summary', models.TextField(max_length=1000)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
